<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" name="SignedbyMMS multicell art" tilewidth="160" tileheight="128" tilecount="29" columns="0" objectalignment="bottomleft">
<tile id="0"><properties><property name="title" value="Jack Nicholson"/><property name="cellsWide" type="int" value="3"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="true"/></properties><image source="frames/00-negative-1.png" width="96" height="128"/></tile>
<tile id="1"><properties><property name="title" value="Heath Ledger"/><property name="cellsWide" type="int" value="3"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="true"/></properties><image source="frames/01-negative-2.png" width="96" height="128"/></tile>
<tile id="2"><properties><property name="title" value="Joaquin Phoenix"/><property name="cellsWide" type="int" value="3"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="true"/></properties><image source="frames/02-negative-3.png" width="96" height="128"/></tile>
<tile id="3"><properties><property name="title" value="Jim Carrey, frame 1"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/03-c1.png" width="128" height="128"/></tile>
<tile id="4"><properties><property name="title" value="Jim Carrey, frame 2"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/04-c2.png" width="128" height="128"/></tile>
<tile id="5"><properties><property name="title" value="Jim Carrey, frame 3"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/05-c3.png" width="128" height="128"/></tile>
<tile id="6"><properties><property name="title" value="Jim Carrey, frame 4"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/06-c4.png" width="128" height="128"/></tile>
<tile id="7"><properties><property name="title" value="Jim Carrey, frame 5"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/07-c5.png" width="128" height="128"/></tile>
<tile id="8"><properties><property name="title" value="Jim Carrey, frame 6"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/08-c6.png" width="128" height="128"/></tile>
<tile id="9"><properties><property name="title" value="Jim Carrey, frame 7"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/09-c7.png" width="128" height="128"/></tile>
<tile id="10"><properties><property name="title" value="Jim Carrey, frame 8"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/10-c8.png" width="128" height="128"/></tile>
<tile id="11"><properties><property name="title" value="Jim Carrey, frame 9"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/11-c9.png" width="128" height="128"/></tile>
<tile id="12"><properties><property name="title" value="Hisoka"/><property name="cellsWide" type="int" value="3"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/12-anime-1.png" width="96" height="128"/></tile>
<tile id="13"><properties><property name="title" value="Roronoa Zoro"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/13-anime-2.png" width="128" height="128"/></tile>
<tile id="14"><properties><property name="title" value="God Usopp"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/14-anime-3.png" width="128" height="128"/></tile>
<tile id="15"><properties><property name="title" value="Sheldon Cooper"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/15-image-1.png" width="128" height="128"/></tile>
<tile id="16"><properties><property name="title" value="Phoebe Buffay"/><property name="cellsWide" type="int" value="3"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/16-image-3.png" width="96" height="128"/></tile>
<tile id="17"><properties><property name="title" value="Giannis Antetokounmpo"/><property name="cellsWide" type="int" value="3"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/17-bb-1.png" width="96" height="128"/></tile>
<tile id="18"><properties><property name="title" value="Air Jordan 1"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/18-image-2.png" width="128" height="128"/></tile>
<tile id="19"><properties><property name="title" value="Joey Tribbiani"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/19-image-5.png" width="128" height="128"/></tile>
<tile id="20"><properties><property name="title" value="Sanji: wanted poster"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/20-anime-4.png" width="128" height="128"/></tile>
<tile id="21"><properties><property name="title" value="Naruto: four chapters"/><property name="cellsWide" type="int" value="5"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/21-anime-5.png" width="160" height="128"/></tile>
<tile id="22"><properties><property name="title" value="Itachi Uchiha"/><property name="cellsWide" type="int" value="3"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/22-anime-6.png" width="96" height="128"/></tile>
<tile id="23"><properties><property name="title" value="Kakashi's team"/><property name="cellsWide" type="int" value="5"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/23-anime-7.png" width="160" height="128"/></tile>
<tile id="24"><properties><property name="title" value="Team 7, then &amp; now"/><property name="cellsWide" type="int" value="3"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/24-anime-8.png" width="96" height="128"/></tile>
<tile id="25"><properties><property name="title" value="Harley Quinn"/><property name="cellsWide" type="int" value="3"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/25-image-4.png" width="96" height="128"/></tile>
<tile id="26"><properties><property name="title" value="Matthew Perry"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/26-image-6.png" width="128" height="128"/></tile>
<tile id="27"><properties><property name="title" value="Irrfan Khan"/><property name="cellsWide" type="int" value="4"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="false"/></properties><image source="frames/27-image-7.png" width="128" height="128"/></tile>
<tile id="28"><properties><property name="title" value="White cat study"/><property name="cellsWide" type="int" value="3"/><property name="cellsHigh" type="int" value="4"/><property name="negative" type="bool" value="true"/></properties><image source="frames/28-negative-4.png" width="96" height="128"/></tile>
</tileset>
